# Generated by Django 5.2.15 on 2026-06-14 18:54

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0006_importanomaly_anomalydecision_importsession_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='expense',
            old_name='date',
            new_name='expense_date',
        ),
        migrations.RenameField(
            model_name='expenseparticipant',
            old_name='share_percentage',
            new_name='percentage',
        ),
        migrations.RemoveField(
            model_name='expense',
            name='notes',
        ),
        migrations.AddField(
            model_name='expense',
            name='split_type',
            field=models.CharField(choices=[('equal', 'Equal'), ('percentage', 'Percentage'), ('exact', 'Exact')], default='equal', max_length=20),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='expense',
            name='group',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.group'),
        ),
        migrations.AlterField(
            model_name='expense',
            name='paid_by',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='core.member'),
        ),
    ]
