# Generated by Django 5.2.15 on 2026-06-14 21:41

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0007_rename_date_expense_expense_date_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='base_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='converted_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='exchange_rate',
            field=models.DecimalField(blank=True, decimal_places=6, max_digits=15, null=True),
        ),
        migrations.AlterField(
            model_name='expense',
            name='split_type',
            field=models.CharField(choices=[('equal', 'Equal'), ('percentage', 'Percentage'), ('exact', 'Exact')], default='equal', max_length=20),
        ),
    ]
