# Generated by Django 5.2.15 on 2026-06-14 22:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('core', '0008_expense_base_currency_expense_converted_amount_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='expense',
            name='original_amount',
            field=models.DecimalField(blank=True, decimal_places=2, max_digits=12, null=True),
        ),
        migrations.AddField(
            model_name='expense',
            name='original_currency',
            field=models.CharField(blank=True, max_length=10, null=True),
        ),
    ]
